name: JobPilot Scheduler

on:
  schedule:
    - cron: "30 14 * * *" # 8 PM IST
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-jobpilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run JobPilot
        run: python job_alert.py
        env: # ← ADD THIS
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
